---

- name: fix php depend issues - libargon
  yum:
    name: "{{ libargon_repo_url }}"
    state: present

- name: fix php depend issues - libtidy
  yum:
    name: "{{ libargon_repo_url }}"
    state: present

- name: fix php depend issues - freetds
  yum:
    name: "{{ freetds_repo_url }}"
    state: present

- name: fix php depend issues - libmcrypt
  yum:
    name: "{{ libmcrypt_repo_url }}"
    state: present

- name: Install php, php-mysql
  action: yum pkg={{item}} state=latest
  with_items:
      - php-cli
      - php
      - php-mysql
  ignore_errors: yes

- name: Install php using yum
  action: yum pkg={{item}} state=latest
  with_items:
      - php-bcmath
      - php-bz2
      - php-calendar
      - php-ctype
      - php-curl
      - php-date
      - php-dom
      - php-ereg
      - php-exif
      - php-fileinfo
      - php-filter
      - php-ftp
      - php-gd
      - php-gettext
      - php-gmp
      - php-hash
      - php-iconv
      - php-json
      - php-libxml
      - php-mbstring
      - php-mcrypt
      - php-mhash
      - php-mysqli
      - php-mysqlnd
      - php-openssl
      - php-pcntl
      - php-pcre
      - php-pdo
      - php-pdo_dblib
      - php-pdo_mysql
      - php-pdo_sqlite
      - php-posix
      - php-readline
      - php-session
      - php-shmop
      - php-soap
      - php-sockets
      - php-sqlite3
      - php-standard
      - php-sysvmsg
      - php-sysvsem
      - php-sysvshm
      - php-tidy
      - php-tokenizer
      - php-wddx
      - php-xml
      - php-xmlreader
      - php-xmlwriter
      - php-xsl
      - php-zip
      - php-zlib
  ignore_errors: yes
  notify: restart apache


  
